### ISSUE TITLE
Benodigde vervoersbewijzen per Route(segment)

### ISSUE THREAD

**Issue by dimi-schepers** [Informatievlaanderen/OSLOthema-mobiliteit-trips-en-aanbod#12]
**Model(len) waarop de issue van toepassing is:**
OSLO Mobiliteit: Trips en Aanbod 

**Omschrijving van het probleem:** 
In het huidige model mis ik het concept “Aan te schaffen vervoersrechten”. Dan zijn de vervoerstitels die nodig zijn om de geplande reis te kunnen maken.  In de toekomst worden dit waarschijnlijk elektronische vervoersbewijzen of zelfs combi-ticketten.

Langs de ontwikkelaarszijde is dit concept ook nodig.  Voor elke mogelijke Route zal aan de Reiziger (rekening houdend met zijn Kenmerk van het type huidige abonnementen) de lijst aangeboden worden van de vervoersrechten die nog moeten aangeschaft worden om voor elk Routesegment een vervoersrecht te hebben. Met de prijs per aan te schaffen recht, kan de reiziger een Route kiezen, niet enkel gebaseerd op duurtijd maar ook op prijs. Mogelijk toont de aanbieder per mogelijke Route meerdere mogelijkheden van aan te schaffen vervoersrechten. Zo kan je voor een treintrip naar de kust een ticket kopen of een Rail Pass. En misschien kan de gebruiker enkele van de aan te schaffen vervoersrechten uitvinken omdat hij bijvoorbeeld nog ergens een Rail Pass liggen heeft.  In elk geval, de reiziger kan uit de mogelijke routes, met kennis van tijdsduur en totale kostprijs (rekening houdend met zijn actieve abonnementen) zijn gekozenRoute met de voorgestelde aan te schaffen vervoersrechten selecteren, misschien nog enkele voorgestelde vervoersrechten uitvinken en daarna de resterende vervoersrechten aanschaffen.

**Omschrijving van een mogelijke oplossing:**
Omdat deze aan te schaffen vervoersrechten voor de aanbieder in een 1 to many relatie aan de mogelijkeRoutes hangt, zou ik de uiteindelijke aangeschafte vervoersrechten ook aan de Route (de gekozenRoute) en niet aan de Reis hangen. Er kan nog nagedacht worden of er een concept “aan te schaffen vervoersrechten” en een andere concept “aangeschafte vervoersrechten” nodig is of deze samen kunnen genomen worden. De structuur is waarschijnlijk identiek.

Peter Peeters
MOW, analist Mobilidata

**Comment by dimi-schepers** [comment]
Ik zie twee zaken die hiervoor gewijzigd zouden moeten worden:

1. We maken de relatie van Vervoersbewijs naar Boeking optioneel, zodat Vervoersbewijs ook gebruikt kan worden voor een voorstel aan de Reiziger (dat daarom nog niet per se al geboekt is). En we linken Routesegment dan aan Vervoersbewijs met kardinaliteit [0..*] (al deze Vervoersbewijzen (Go Pass, Rail Pass, ... ) zijn ok om te gebruiken voor dit segment).

2. We herdefiniëren de relatie _gerealiseerd door_ om deze relatie ook te kunnen gebruiken in het kader van een mogelijke Route (en dus niet alleen voor een uitgevoerde Route): een Routesegment wordt potentieel uitgevoerd met deze Dienst (en met dit Vervoersbewijs).

In een MaaS-situatie, waar er één Dienst en één Vervoersbewijs is voor meerdere Routesegmenten, zou ik het niet onnodig complex maken door dezelfde relaties nog eens van Route naar Vervoersbewijs en Dienst te trekken, maar zou ik dit oplossen door voor ieder Routesegment te verwijzen naar dezelfde Dienst en hetzelfde Vervoerbewijs.

**Comment by pomgod** [comment]
Heb je binnen TOMP niet een status voor een boeking die dit omvat? Valt dit niet onder "New" of "Pending". Iedere vraag voor een route is een potentiële boeking.

**Comment by GeertThijs** [comment]
> Ik zie twee zaken die hiervoor gewijzigd zouden moeten worden:
> 
> 1. We maken de relatie van Vervoersbewijs naar Boeking optioneel, zodat Vervoersbewijs ook gebruikt kan worden voor een voorstel aan de Reiziger (dat daarom nog niet per se al geboekt is). En we linken Routesegment dan aan Vervoersbewijs met kardinaliteit [0..*] (al deze Vervoersbewijzen (Go Pass, Rail Pass, ... ) zijn ok om te gebruiken voor dit segment).
> 2. We herdefiniëren de relatie _gerealiseerd door_ om deze relatie ook te kunnen gebruiken in het kader van een mogelijke Route (en dus niet alleen voor een uitgevoerde Route): een Routesegment wordt potentieel uitgevoerd met deze Dienst (en met dit Vervoersbewijs).
> 
> In een MaaS-situatie, waar er één Dienst en één Vervoersbewijs is voor meerdere Routesegmenten, zou ik het niet onnodig complex maken door dezelfde relaties nog eens van Route naar Vervoersbewijs en Dienst te trekken, maar zou ik dit oplossen door voor ieder Routesegment te verwijzen naar dezelfde Dienst en hetzelfde Vervoerbewijs.

Mbt punt 1:

- De associatie loopt van Boeking naar Vervoersbewijs. Maar het komt op hetzelfde neer: je kan een Vervoersbewijs opvoeren nog voor de Reis is vastgelegd door een Boeking.

- De associatie Routesegment-Vervoersbewijs is intussen toegevoegd. Het is dus mogelijk om segmenten van mogelijke routes aan (evt nog niet aangeschafte) Vervoersbewijzen te koppelen.

Mbt punt 2:

- De definitie van Routesegment.vervoersbewijs werd intussen overeenkomstig aangepast: "Vervoersbewijs waarmee het Routesegment kan worden afgelegd of is afgelegd.".

**Comment by GeertThijs** [comment]
> Heb je binnen TOMP niet een status voor een boeking die dit omvat? Valt dit niet onder "New" of "Pending". Iedere vraag voor een route is een potentiële boeking.

- Binnen [TOMP](https://github.com/TOMP-WG/TOMP-API/blob/master/documents/191021%20-%20Blueprint%20for%20a%20TO-MP%20API%20v1.1.pdf) heb je (vrij vertaald): aangevraagd, hangende, vrijgegeven, vervallen, bevestigd, verworpen. Geen status voor een tentatieve Boeking dus. 
- Maar gezien voornoemde oplossingen is deze niet langer nodig volgens mij.
