### ISSUE TITLE
Verken het vocabularium: ttl file niet aanwezig

### ISSUE THREAD

**Issue by MatisseGh** [Informatievlaanderen/OSLOthema-mobiliteit-trips-en-aanbod#36]
Na klikken op de link [Verken het vocabularium](http://visualdataweb.de/webvowl/#iri=https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod.ttl)  in `https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod` is het ttl bestand niet vindbaar op  `https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod.ttl` .

**Comment by KristofVDB1** [comment]
`https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod.ttl` is intussen beschikbaar gemaakt.
