### ISSUE TITLE
Codelijst vervoermiddel

### ISSUE THREAD

**Issue by pomgod** [Informatievlaanderen/OSLOthema-mobiliteit-trips-en-aanbod#5]
Micromobility heeft een voorstel tot nieuwe voertuigcategorie actie die volgens mij wel zinvol kan zijn. Mss interessant om te bekijken. ![Uploading IMG_20191025_065632.jpg…]()

**Comment by pietercolpaert** [comment]
Mijn voorstel wat als hoofdtaxonomie de juridische definities te gebruiken, en daarronder meer specifieke modi te steken. Bvb. Speed pedelec is juridisch anders dan elektrische fiets.

**Comment by dimi-schepers** [comment]
Voorgestelde toevoegingen:
- shuttle
- elektrischeShuttle
- autonomeShuttle
- elektrischeWagen
- elektrischeBus
- elektrischeStep

Peter Van der Perre (ITS)

**Comment by dimi-schepers** [comment]
Voorstel: 
- te voet
- fiets
- scooter/moped
- step
- auto
- bus
- boot
- trein
- vliegtuig
- parkeren
- verschillende modi
- service
- voortbewegingstoestel
- tram

Stijn Vernaillen (Stad Antwerpen)

**Comment by pomgod** [comment]
> Voorgestelde toevoegingen:
> 
> * shuttle
> * elektrischeShuttle
> * autonomeShuttle
> * elektrischeWagen
> * elektrischeBus
> * elektrischeStep
> 
> Peter Van der Perre (ITS)

Ik zou de modus los houden van de technische aspecten.
