### ISSUE TITLE
Wijzigen baseuri voor vocabularium + verwarrende naam voor deze repository

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-mobiliteit-trips-en-aanbod#8]
(1)
De baseuri voor het vocabularium dat we hier definiëren wordt op dit ogenblik verondersteld te zijn:
https://data.vlaanderen.be/ns/mobiliteit#. Zie ook #1 .
Dit kan niet, want deze uri is al bezet (volg hem maar eens).
Voorstel: wijzigen naar
**https://data.vlaanderen.be/ns/deelmobiliteit#**.
(2)
Om verwarring te vermijden zou ik voorstellen om meteen ook de naam van deze repository te veranderen in **OSLOthema-deelmobiliteit**. Iedereen zou wel zijn links moeten aanpassen, maar liever korte pijn dan lang lijden...

**Comment by pomgod** [comment]
"Deelmobiliteit" dekt ook niet helemaal de lading. Het gaat ook over de andere mobiliteitsoplossingen. Ik zou dan eerder richting "MaaS"; "Mobility-as-a-Service"; "Mobiliteit-als-een-dienst"; "MoDi" (Mobiliteit als een dienst); "MaD" (mobiliteit-als-dienst)

**Comment by mvanbrab** [comment]
We vonden gezien het vocabularium enerzijds trips en anderzijds het aanbod beschrijft, volgende aanpassingen gepast:

Naam vocabularium:
OSLO-Mobiliteit: Trips & Aanbod
baseURI vocabularium:
https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#.

Naam en URL van deze repository: 
OSLOthema-mobiliteit-trips-en-aanbod
https://github.com/Informatievlaanderen/OSLOthema-mobiliteit-trips-en-aanbod
