### ISSUE TITLE
Uitvoerder: Agent ipv GeregistreerdeOrganisatie?

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-mobiliteit-trips-en-aanbod#9]
**Link waar het probleem zich voor doet:**
https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/mobiliteit-trips-en-aanbod/ontwerpstandaard/20191216

**Omschrijving van het probleem:**
Is de Uitvoerder steeds een GeregistreerdeOrganisatie? Wat bv met Mobiliteitsdiensten als UBER die privépersonen als Uitvoerder inzetten. 

**Omschrijving van een mogelijke oplossing:**
Agent ipv GeregistreerdeOrganisatie maken van Uitvoerder.

**Comment by GeertThijs** [comment]
- Agent is abstract in OSLO-Generiek. Maw: bij implementatie zal het type Agent (Persoon, Organisatie... ) moeten worden opgegeven. Of we modelleren dit expliciet uit, ttz de mogelijke subklassen zetten we (met hun attributen) in het diagram. Als we Agent niet uitmodelleren: huidig minimaal aantal attributen, ttz registratie, naam, contactinfo? En bijkomend; type?
- Graag wat meer use cases dan enkel Uber? Het lijkt wel te kloppen dat personen werkzaam in de deeleconomie geen ondernemingsnummer moeten hebben. Zie https://www.acerta.be/nl/starters/startersvragen/inschrijving-in-de-kruispuntbank-van-ondernemingen/ondernemingsnummer-aanvragen.

**Comment by pomgod** [comment]
Ik denk dat de vraag hierbij vooral is hoe ver we gaan. Enerzijds wil ik op de één of andere manier wel meer informatie over die bestuurder hebben maar anderzijds is dit mss iets dat de mobiliteitsaanbieder als bijkomende data bij zijn dienst moet meesturen. Dus meer als vrije informatie?
